export const products = [
  {
    index: 1,
    title: "Pasteis",
    description: "lorem ipsulum dolor",
    img: "./img/images/aloo.png",
    value: 35,
    rating: 4.5,
    deliveryTime: 25,
  },
  {
    index: 2,

    title: "Bolinho de nozes",
    description: "lorem ipsulum dolor",
    img: "./img/images/bakked.png",
    value: 55,
    rating: 4.5,
    deliveryTime: 25,
  },
  {
    index: 3,
    title: "Bowl",
    description: "lorem ipsulum dolor",
    img: "./img/images/bowl.png",
    value: 78,
    rating: 4.1,
    deliveryTime: 35,
  },
  {
    index: 4,
    title: "Mexicano",
    description: "lorem ipsulum dolor",
    img: "./img/images/mexican.png",
    value: 12,
    rating: 3.8,
    deliveryTime: 10,
  },
  {
    index: 5,
    title: "Mix de Frutas",
    description: "lorem ipsulum dolor",
    img: "./img/images/mixed.png",
    value: 78,
    rating: 4.5,
    deliveryTime: 50,
  },
  {
    index: 6,
    title: "Sopa Panner",
    description: "lorem ipsulum dolor",
    img: "./img/images/panner.png",
    value: 85,
    rating: 4.1,
    deliveryTime: 30,
  },
  {
    index: 7,
    title: "Pizza",
    description: "lorem ipsulum dolor",
    img: "./img/images/pizza.png",
    value: 75,
    rating: 4.0,
    deliveryTime: 35,
  },
  {
    index: 8,
    title: "Ramachandra",
    description: "lorem ipsulum dolor",
    img: "./img/images/ramachandra.png",
    value: 25,
    rating: 4.9,
    deliveryTime: 55,
  },
  {
    index: 9,
    title: "Frango Empanado",
    description: "lorem ipsulum dolor",
    img: "./img/images/southwest.png",
    value: 45,
    rating: 4.5,
    deliveryTime: 25,
  },
  {
    index: 10,
    title: "Swap de Nozes",
    description: "lorem ipsulum dolor",
    img: "./img/images/swap.png",
    value: 105,
    rating: 4.5,
    deliveryTime: 25,
  },
  {
    index: 11,
    title: "Vegetariano",
    description: "lorem ipsulum dolor",
    img: "./img/images/vegetarian.png",
    value: 45,
    rating: 3.8,
    deliveryTime: 45,
  },
];
